
name: Meu Primeiro CI - MASTER
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  GrupoTeste:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Usando MASTER
        run: echo Executando na master!!

      - name: Primeiro Tarefa
        run: echo Executando o que solicitei!!

      - name: Segunda Tarefa
        run: |
          echo Segundo comando em execucao
          echo Projeto Teste.
